# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_full_striptags',
            field=models.TextField(default='text', help_text='без html тегов', verbose_name='полное описание'),
            preserve_default=False,
        ),
    ]
