# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_description_full_striptags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=250, verbose_name='название'),
        ),
    ]
