# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170601_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.CharField(blank=True, max_length=100, verbose_name='стоимость'),
        ),
    ]
