# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170601_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='в архиве'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='удалено'),
        ),
    ]
