# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170601_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(unique=True, verbose_name='ссылка'),
        ),
    ]
